package generator

import (
	"fmt"
	"strings"

	"github.com/bryanathallah/db-schema-differ/models"
)

type MySQLGenerator struct{}

func NewMySQLGenerator() Generator {
	return &MySQLGenerator{}
}

func (g *MySQLGenerator) Generate(diff *models.SchemaDiff, sourceSchema *models.Schema, options GenOptions) ([]string, error) {
	var statements []string

	statements = append(statements,
		"-- ============================================================",
		"-- Generated by db-schema-differ",
		"-- !! MySQL does not support transactional DDL !!",
		"-- !! If this script fails mid-way, changes CANNOT be rolled back !!",
		"-- !! Use the state file (--resume) to continue from where it failed !!",
		"-- ============================================================",
		"",
	)

	// Filter and group changes by table actions
	var tablesToCreate []string
	var tablesToDrop []string
	var tablesToModify []models.TableDiff

	for _, tDiff := range diff.Tables {
		switch tDiff.Action {
		case models.ActionAdd:
			tablesToCreate = append(tablesToCreate, tDiff.TableName)
		case models.ActionDrop:
			if !options.SafeOnly {
				tablesToDrop = append(tablesToDrop, tDiff.TableName)
			}
		case models.ActionModify:
			tablesToModify = append(tablesToModify, tDiff)
		}
	}

	// -------------------------------------------------------------
	// PASS 1: STRUCTURE PASS (CREATE / DROP TABLES)
	// -------------------------------------------------------------
	pass1Statements := []string{}
	pass1Statements = append(pass1Statements,
		"-- ============================================================",
		"-- PASS 1: STRUCTURE (CREATE/DROP TABLES)",
		"-- ============================================================",
	)

	// 1a. Drop foreign keys on tables that will be dropped (handled by CASCADE or Pass 3)

	// 1b. Drop tables
	for _, tableName := range tablesToDrop {
		pass1Statements = append(pass1Statements, fmt.Sprintf("DROP TABLE IF EXISTS `%s`;", tableName))
	}

	// 1c. Create tables (without FKs)
	sortedTables, warnings := sortTablesTopologically(tablesToCreate, sourceSchema)
	for _, warn := range warnings {
		pass1Statements = append(pass1Statements, fmt.Sprintf("-- WARNING: %s", warn))
	}

	for _, tableName := range sortedTables {
		sTable := sourceSchema.Tables[tableName]
		var createCols []string

		// Add column definitions
		for _, colName := range sTable.ColumnOrder {
			col := sTable.Columns[colName]
			colDef := formatMySQLColumnDef(col)
			createCols = append(createCols, "  "+colDef)
		}

		// Add Primary Key if exists
		for _, idx := range sTable.Indexes {
			if idx.Type == "PRIMARY" {
				createCols = append(createCols, fmt.Sprintf("  PRIMARY KEY (%s)", formatIndexColumns(idx.Columns)))
				break
			}
		}

		// Add Non-FK Indexes in CREATE TABLE directly to make it clean,
		// or defer them to pass 3. Direct creation is cleaner for new tables.
		for idxName, idx := range sTable.Indexes {
			if idx.Type == "PRIMARY" {
				continue
			}
			unique := ""
			if idx.Type == "UNIQUE" {
				unique = "UNIQUE "
			} else if idx.Type == "FULLTEXT" {
				unique = "FULLTEXT "
			}
			createCols = append(createCols, fmt.Sprintf("  %sKEY `%s` (%s)", unique, idxName, formatIndexColumns(idx.Columns)))
		}

		tableOpts := ""
		if sTable.Engine != "" {
			tableOpts += fmt.Sprintf(" ENGINE=%s", sTable.Engine)
		}
		if sTable.Collation != "" {
			tableOpts += fmt.Sprintf(" DEFAULT CHARSET=%s", strings.Split(sTable.Collation, "_")[0])
			tableOpts += fmt.Sprintf(" COLLATE=%s", sTable.Collation)
		}
		if sTable.Comment != "" {
			tableOpts += fmt.Sprintf(" COMMENT='%s'", escapeSQL(sTable.Comment))
		}

		createSQL := fmt.Sprintf("CREATE TABLE `%s` (\n%s\n)%s;", tableName, strings.Join(createCols, ",\n"), tableOpts)
		pass1Statements = append(pass1Statements, createSQL)
	}

	if len(tablesToDrop) > 0 || len(tablesToCreate) > 0 {
		statements = append(statements, pass1Statements...)
		statements = append(statements, "")
	}

	// -------------------------------------------------------------
	// PASS 2: COLUMN PASS (ALTERS ON COLUMNS AND INDEXES)
	// -------------------------------------------------------------
	pass2Statements := []string{}
	pass2Statements = append(pass2Statements,
		"-- ============================================================",
		"-- PASS 2: COLUMN PASS (ALTER COLUMNS / INDEXES)",
		"-- ============================================================",
	)

	hasPass2 := false
	for _, tDiff := range tablesToModify {
		tableName := tDiff.TableName
		sTable := sourceSchema.Tables[tableName]

		// 2a. Drop Indexes that are being removed or modified
		for _, idxDiff := range tDiff.Indexes {
			if idxDiff.Action == models.ActionDrop {
				if idxDiff.OldIndex.Type == "PRIMARY" {
					pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE `%s` DROP PRIMARY KEY;", tableName))
				} else {
					pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE `%s` DROP INDEX `%s`;", tableName, idxDiff.IndexName))
				}
				hasPass2 = true
			}
		}

		// 2b. Drop Columns (unmatched)
		for _, colDiff := range tDiff.Columns {
			if colDiff.Action == models.ActionDrop && !options.SafeOnly {
				pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE `%s` DROP COLUMN `%s`;", tableName, colDiff.ColumnName))
				hasPass2 = true
			}
		}

		// 2c. Add Columns (with correct positioning)
		for _, colDiff := range tDiff.Columns {
			if colDiff.Action == models.ActionAdd {
				newCol := colDiff.NewColumn
				positionClause := ""
				// Find position in source schema
				for idx, name := range sTable.ColumnOrder {
					if name == newCol.Name {
						if idx == 0 {
							positionClause = " FIRST"
						} else {
							positionClause = " AFTER `" + sTable.ColumnOrder[idx-1] + "`"
						}
						break
					}
				}

				colDef := formatMySQLColumnDef(*newCol)
				pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE `%s` ADD COLUMN %s%s;", tableName, colDef, positionClause))
				hasPass2 = true
			}
		}

		// 2d. Modify Columns
		for _, colDiff := range tDiff.Columns {
			if colDiff.Action == models.ActionModify {
				newCol := colDiff.NewColumn
				colDef := formatMySQLColumnDef(*newCol)
				pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE `%s` MODIFY COLUMN %s;", tableName, colDef))
				hasPass2 = true
			}
		}
	}

	if hasPass2 {
		statements = append(statements, pass2Statements...)
		statements = append(statements, "")
	}

	// -------------------------------------------------------------
	// PASS 3: CONSTRAINT PASS (FOREIGN KEYS AND REMAINING INDEXES)
	// -------------------------------------------------------------
	pass3Statements := []string{}
	pass3Statements = append(pass3Statements,
		"-- ============================================================",
		"-- PASS 3: CONSTRAINT PASS (FOREIGN KEYS / INDEXES)",
		"-- ============================================================",
	)

	hasPass3 := false

	// 3a. Drop FKs first
	for _, tDiff := range tablesToModify {
		tableName := tDiff.TableName
		for _, fkDiff := range tDiff.ForeignKeys {
			if fkDiff.Action == models.ActionDrop && !options.SafeOnly {
				pass3Statements = append(pass3Statements, fmt.Sprintf("ALTER TABLE `%s` DROP FOREIGN KEY `%s`;", tableName, fkDiff.FKName))
				hasPass3 = true
			}
		}
	}

	// 3b. Add Indexes for modified tables
	for _, tDiff := range tablesToModify {
		tableName := tDiff.TableName
		for _, idxDiff := range tDiff.Indexes {
			if idxDiff.Action == models.ActionAdd {
				idx := idxDiff.NewIndex
				if idx.Type == "PRIMARY" {
					pass3Statements = append(pass3Statements, fmt.Sprintf("ALTER TABLE `%s` ADD PRIMARY KEY (%s);", tableName, formatIndexColumns(idx.Columns)))
				} else {
					unique := ""
					if idx.Type == "UNIQUE" {
						unique = "UNIQUE "
					} else if idx.Type == "FULLTEXT" {
						unique = "FULLTEXT "
					}
					pass3Statements = append(pass3Statements, fmt.Sprintf("ALTER TABLE `%s` ADD %sINDEX `%s` (%s);", tableName, unique, idx.Name, formatIndexColumns(idx.Columns)))
				}
				hasPass3 = true
			}
		}
	}

	// 3c. Add Foreign Keys for created tables
	for _, tableName := range sortedTables {
		sTable := sourceSchema.Tables[tableName]
		for fkName, fk := range sTable.ForeignKeys {
			fkSQL := fmt.Sprintf("ALTER TABLE `%s` ADD CONSTRAINT `%s` FOREIGN KEY (`%s`) REFERENCES `%s` (`%s`)",
				tableName, fkName, fk.Column, fk.ReferencedTable, fk.ReferencedColumn)
			if fk.OnDelete != "" && strings.ToUpper(fk.OnDelete) != "NO ACTION" {
				fkSQL += " ON DELETE " + fk.OnDelete
			}
			if fk.OnUpdate != "" && strings.ToUpper(fk.OnUpdate) != "NO ACTION" {
				fkSQL += " ON UPDATE " + fk.OnUpdate
			}
			pass3Statements = append(pass3Statements, fkSQL+";")
			hasPass3 = true
		}
	}

	// 3d. Add Foreign Keys for modified tables
	for _, tDiff := range tablesToModify {
		tableName := tDiff.TableName
		for _, fkDiff := range tDiff.ForeignKeys {
			if fkDiff.Action == models.ActionAdd {
				fk := fkDiff.NewFK
				fkSQL := fmt.Sprintf("ALTER TABLE `%s` ADD CONSTRAINT `%s` FOREIGN KEY (`%s`) REFERENCES `%s` (`%s`)",
					tableName, fk.Name, fk.Column, fk.ReferencedTable, fk.ReferencedColumn)
				if fk.OnDelete != "" && strings.ToUpper(fk.OnDelete) != "NO ACTION" {
					fkSQL += " ON DELETE " + fk.OnDelete
				}
				if fk.OnUpdate != "" && strings.ToUpper(fk.OnUpdate) != "NO ACTION" {
					fkSQL += " ON UPDATE " + fk.OnUpdate
				}
				pass3Statements = append(pass3Statements, fkSQL+";")
				hasPass3 = true
			}
		}
	}

	if hasPass3 {
		statements = append(statements, pass3Statements...)
		statements = append(statements, "")
	}

	return statements, nil
}

// formatMySQLColumnDef formats a column structure into MySQL DDL definition.
func formatMySQLColumnDef(col models.Column) string {
	parts := []string{"`" + col.Name + "`", col.RawType}

	if col.Nullable == "NO" {
		parts = append(parts, "NOT NULL")
	} else {
		parts = append(parts, "NULL")
	}

	if col.DefaultValue != nil {
		parts = append(parts, "DEFAULT "+formatMySQLDefaultValue(col.RawType, *col.DefaultValue))
	}

	if col.AutoIncrement {
		parts = append(parts, "AUTO_INCREMENT")
	}

	if col.Collation != "" {
		parts = append(parts, "COLLATE "+col.Collation)
	}

	if col.Comment != "" {
		parts = append(parts, fmt.Sprintf("COMMENT '%s'", escapeSQL(col.Comment)))
	}

	return strings.Join(parts, " ")
}

func formatMySQLDefaultValue(rawType, def string) string {
	defLower := strings.ToLower(def)
	// Check if default is a function/expression or a literal value
	if defLower == "current_timestamp" || strings.Contains(defLower, "current_timestamp(") {
		return def
	}
	// Literal value should be quoted unless numeric
	if strings.Contains(defLower, "'") || strings.Contains(defLower, "\"") {
		return def
	}
	// Keep numeric literals unquoted, quote others
	switch strings.ToLower(strings.Split(rawType, "(")[0]) {
	case "int", "integer", "bigint", "smallint", "tinyint", "mediumint", "decimal", "float", "double":
		return def
	default:
		return fmt.Sprintf("'%s'", escapeSQL(def))
	}
}

func formatIndexColumns(cols []string) string {
	var formatted []string
	for _, c := range cols {
		formatted = append(formatted, "`"+c+"`")
	}
	return strings.Join(formatted, ", ")
}

func escapeSQL(s string) string {
	return strings.ReplaceAll(s, "'", "''")
}

// sortTablesTopologically sorts the tables to create using a topological dependency resolver.
func sortTablesTopologically(tables []string, sourceSchema *models.Schema) ([]string, []string) {
	adj := make(map[string][]string) // adjacency list: parent -> list of children
	inDegree := make(map[string]int)
	tableSet := make(map[string]bool)

	for _, t := range tables {
		tableSet[t] = true
		inDegree[t] = 0
	}

	// Build dependency graph
	for _, t := range tables {
		sTable := sourceSchema.Tables[t]
		for _, fk := range sTable.ForeignKeys {
			refTable := fk.ReferencedTable
			// We only care about dependencies between tables that are being created *in this run*
			if tableSet[refTable] && refTable != t {
				adj[refTable] = append(adj[refTable], t)
				inDegree[t]++
			}
		}
	}

	// Kahn's algorithm for topological sorting
	var queue []string
	for _, t := range tables {
		if inDegree[t] == 0 {
			queue = append(queue, t)
		}
	}

	var sorted []string
	var warnings []string

	for len(queue) > 0 {
		// Dequeue
		curr := queue[0]
		queue = queue[1:]
		sorted = append(sorted, curr)

		for _, child := range adj[curr] {
			inDegree[child]--
			if inDegree[child] == 0 {
				queue = append(queue, child)
			}
		}
	}

	// If sorted count < table count, there is a circular dependency
	if len(sorted) < len(tables) {
		// Find remaining tables in dependency cycle
		var remaining []string
		for _, t := range tables {
			found := false
			for _, s := range sorted {
				if s == t {
					found = true
					break
				}
			}
			if !found {
				remaining = append(remaining, t)
			}
		}
		warnings = append(warnings, fmt.Sprintf("Circular dependency detected among tables: %s. Order is fallback-sequential.", strings.Join(remaining, ", ")))
		// Append remaining tables in any order so they still get created
		sorted = append(sorted, remaining...)
	}

	return sorted, warnings
}
