package generator

import (
	"fmt"
	"strings"

	"github.com/bryanathallah/db-schema-differ/models"
)

type PostgresGenerator struct{}

func NewPostgresGenerator() Generator {
	return &PostgresGenerator{}
}

func (g *PostgresGenerator) Generate(diff *models.SchemaDiff, sourceSchema *models.Schema, options GenOptions) ([]string, error) {
	var statements []string

	statements = append(statements,
		"BEGIN;",
		"-- ============================================================",
		"-- Generated by db-schema-differ",
		"-- Wrapped in a single PostgreSQL transaction block",
		"-- ============================================================",
		"",
	)

	// Filter and group changes by table actions
	var tablesToCreate []string
	var tablesToDrop []string
	var tablesToModify []models.TableDiff

	for _, tDiff := range diff.Tables {
		switch tDiff.Action {
		case models.ActionAdd:
			tablesToCreate = append(tablesToCreate, tDiff.TableName)
		case models.ActionDrop:
			if !options.SafeOnly {
				tablesToDrop = append(tablesToDrop, tDiff.TableName)
			}
		case models.ActionModify:
			tablesToModify = append(tablesToModify, tDiff)
		}
	}

	// -------------------------------------------------------------
	// PASS 1: STRUCTURE PASS (CREATE / DROP TABLES)
	// -------------------------------------------------------------
	pass1Statements := []string{}
	pass1Statements = append(pass1Statements,
		"-- ============================================================",
		"-- PASS 1: STRUCTURE (CREATE/DROP TABLES)",
		"-- ============================================================",
	)

	// 1a. Drop tables
	for _, tableName := range tablesToDrop {
		pass1Statements = append(pass1Statements, fmt.Sprintf("DROP TABLE IF EXISTS \"%s\" CASCADE;", tableName))
	}

	// 1b. Create tables (without FKs)
	sortedTables, warnings := sortTablesTopologically(tablesToCreate, sourceSchema)
	for _, warn := range warnings {
		pass1Statements = append(pass1Statements, fmt.Sprintf("-- WARNING: %s", warn))
	}

	for _, tableName := range sortedTables {
		sTable := sourceSchema.Tables[tableName]
		var createCols []string

		// Add column definitions
		for _, colName := range sTable.ColumnOrder {
			col := sTable.Columns[colName]
			colDef := formatPostgresColumnDef(col)
			createCols = append(createCols, "  "+colDef)
		}

		// Add Primary Key if exists
		for _, idx := range sTable.Indexes {
			if idx.Type == "PRIMARY" {
				createCols = append(createCols, fmt.Sprintf("  PRIMARY KEY (%s)", formatPGIndexColumns(idx.Columns)))
				break
			}
		}

		createSQL := fmt.Sprintf("CREATE TABLE \"%s\" (\n%s\n);", tableName, strings.Join(createCols, ",\n"))
		pass1Statements = append(pass1Statements, createSQL)

		// Add table comment
		if sTable.Comment != "" {
			pass1Statements = append(pass1Statements, fmt.Sprintf("COMMENT ON TABLE \"%s\" IS '%s';", tableName, escapeSQL(sTable.Comment)))
		}

		// Add comments for columns in newly created tables
		for _, colName := range sTable.ColumnOrder {
			col := sTable.Columns[colName]
			if col.Comment != "" {
				pass1Statements = append(pass1Statements, fmt.Sprintf("COMMENT ON COLUMN \"%s\".\"%s\" IS '%s';", tableName, col.Name, escapeSQL(col.Comment)))
			}
		}
	}

	if len(tablesToDrop) > 0 || len(tablesToCreate) > 0 {
		statements = append(statements, pass1Statements...)
		statements = append(statements, "")
	}

	// -------------------------------------------------------------
	// PASS 2: COLUMN PASS (ALTERS ON COLUMNS AND INDEXES)
	// -------------------------------------------------------------
	pass2Statements := []string{}
	pass2Statements = append(pass2Statements,
		"-- ============================================================",
		"-- PASS 2: COLUMN PASS (ALTER COLUMNS / INDEXES)",
		"-- ============================================================",
	)

	hasPass2 := false
	for _, tDiff := range tablesToModify {
		tableName := tDiff.TableName

		// 2a. Drop Indexes that are being removed or modified
		for _, idxDiff := range tDiff.Indexes {
			if idxDiff.Action == models.ActionDrop {
				if idxDiff.OldIndex.Type != "PRIMARY" {
					pass2Statements = append(pass2Statements, fmt.Sprintf("DROP INDEX IF EXISTS \"%s\";", idxDiff.IndexName))
					hasPass2 = true
				}
			}
		}

		// 2b. Drop Columns (unmatched)
		for _, colDiff := range tDiff.Columns {
			if colDiff.Action == models.ActionDrop && !options.SafeOnly {
				pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE \"%s\" DROP COLUMN IF EXISTS \"%s\";", tableName, colDiff.ColumnName))
				hasPass2 = true
			}
		}

		// 2c. Add Columns
		for _, colDiff := range tDiff.Columns {
			if colDiff.Action == models.ActionAdd {
				newCol := colDiff.NewColumn
				colDef := formatPostgresColumnDef(*newCol)
				pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE \"%s\" ADD COLUMN %s;", tableName, colDef))

				// Column comment if any
				if newCol.Comment != "" {
					pass2Statements = append(pass2Statements, fmt.Sprintf("COMMENT ON COLUMN \"%s\".\"%s\" IS '%s';", tableName, newCol.Name, escapeSQL(newCol.Comment)))
				}
				hasPass2 = true
			}
		}

		// 2d. Modify Columns
		for _, colDiff := range tDiff.Columns {
			if colDiff.Action == models.ActionModify {
				newCol := colDiff.NewColumn
				oldCol := colDiff.OldColumn

				// Type changed
				if newCol.NormalizedType != oldCol.NormalizedType {
					// Use USING clause for safe casts
					usingClause := fmt.Sprintf(" USING \"%s\"::%s", newCol.Name, newCol.NormalizedType)
					pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE \"%s\" ALTER COLUMN \"%s\" TYPE %s%s;", tableName, newCol.Name, newCol.RawType, usingClause))
				}

				// Nullability changed
				if newCol.Nullable != oldCol.Nullable {
					if newCol.Nullable == "NO" {
						pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE \"%s\" ALTER COLUMN \"%s\" SET NOT NULL;", tableName, newCol.Name))
					} else {
						pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE \"%s\" ALTER COLUMN \"%s\" DROP NOT NULL;", tableName, newCol.Name))
					}
				}

				// Default changed
				sDef := getDefStr(newCol.DefaultValue)
				tDef := getDefStr(oldCol.DefaultValue)
				if sDef != tDef {
					if newCol.DefaultValue == nil {
						pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE \"%s\" ALTER COLUMN \"%s\" DROP DEFAULT;", tableName, newCol.Name))
					} else {
						pass2Statements = append(pass2Statements, fmt.Sprintf("ALTER TABLE \"%s\" ALTER COLUMN \"%s\" SET DEFAULT %s;", tableName, newCol.Name, *newCol.DefaultValue))
					}
				}

				// Comment changed
				if newCol.Comment != oldCol.Comment {
					pass2Statements = append(pass2Statements, fmt.Sprintf("COMMENT ON COLUMN \"%s\".\"%s\" IS '%s';", tableName, newCol.Name, escapeSQL(newCol.Comment)))
				}
				hasPass2 = true
			}
		}
	}

	if hasPass2 {
		statements = append(statements, pass2Statements...)
		statements = append(statements, "")
	}

	// -------------------------------------------------------------
	// PASS 3: CONSTRAINT PASS (FOREIGN KEYS AND REMAINING INDEXES)
	// -------------------------------------------------------------
	pass3Statements := []string{}
	pass3Statements = append(pass3Statements,
		"-- ============================================================",
		"-- PASS 3: CONSTRAINT PASS (FOREIGN KEYS / INDEXES)",
		"-- ============================================================",
	)

	hasPass3 := false

	// 3a. Drop FKs first
	for _, tDiff := range tablesToModify {
		tableName := tDiff.TableName
		for _, fkDiff := range tDiff.ForeignKeys {
			if fkDiff.Action == models.ActionDrop && !options.SafeOnly {
				pass3Statements = append(pass3Statements, fmt.Sprintf("ALTER TABLE \"%s\" DROP CONSTRAINT IF EXISTS \"%s\";", tableName, fkDiff.FKName))
				hasPass3 = true
			}
		}
	}

	// 3b. Add Indexes for modified tables
	for _, tDiff := range tablesToModify {
		tableName := tDiff.TableName
		for _, idxDiff := range tDiff.Indexes {
			if idxDiff.Action == models.ActionAdd {
				idx := idxDiff.NewIndex
				if idx.Type == "PRIMARY" {
					pass3Statements = append(pass3Statements, fmt.Sprintf("ALTER TABLE \"%s\" ADD PRIMARY KEY (%s);", tableName, formatPGIndexColumns(idx.Columns)))
				} else {
					unique := ""
					if idx.Type == "UNIQUE" {
						unique = "UNIQUE "
					}
					pass3Statements = append(pass3Statements, fmt.Sprintf("CREATE %sINDEX \"%s\" ON \"%s\" (%s);", unique, idx.Name, tableName, formatPGIndexColumns(idx.Columns)))
				}
				hasPass3 = true
			}
		}
	}

	// 3c. Add Foreign Keys for created tables
	for _, tableName := range sortedTables {
		sTable := sourceSchema.Tables[tableName]
		for fkName, fk := range sTable.ForeignKeys {
			fkSQL := fmt.Sprintf("ALTER TABLE \"%s\" ADD CONSTRAINT \"%s\" FOREIGN KEY (\"%s\") REFERENCES \"%s\" (\"%s\")",
				tableName, fkName, fk.Column, fk.ReferencedTable, fk.ReferencedColumn)
			if fk.OnDelete != "" && strings.ToUpper(fk.OnDelete) != "NO ACTION" {
				fkSQL += " ON DELETE " + fk.OnDelete
			}
			if fk.OnUpdate != "" && strings.ToUpper(fk.OnUpdate) != "NO ACTION" {
				fkSQL += " ON UPDATE " + fk.OnUpdate
			}
			pass3Statements = append(pass3Statements, fkSQL+";")
			hasPass3 = true
		}
	}

	// 3d. Add Foreign Keys for modified tables
	for _, tDiff := range tablesToModify {
		tableName := tDiff.TableName
		for _, fkDiff := range tDiff.ForeignKeys {
			if fkDiff.Action == models.ActionAdd {
				fk := fkDiff.NewFK
				fkSQL := fmt.Sprintf("ALTER TABLE \"%s\" ADD CONSTRAINT \"%s\" FOREIGN KEY (\"%s\") REFERENCES \"%s\" (\"%s\")",
					tableName, fk.Name, fk.Column, fk.ReferencedTable, fk.ReferencedColumn)
				if fk.OnDelete != "" && strings.ToUpper(fk.OnDelete) != "NO ACTION" {
					fkSQL += " ON DELETE " + fk.OnDelete
				}
				if fk.OnUpdate != "" && strings.ToUpper(fk.OnUpdate) != "NO ACTION" {
					fkSQL += " ON UPDATE " + fk.OnUpdate
				}
				pass3Statements = append(pass3Statements, fkSQL+";")
				hasPass3 = true
			}
		}
	}

	if hasPass3 {
		statements = append(statements, pass3Statements...)
		statements = append(statements, "")
	}

	statements = append(statements, "COMMIT;")

	return statements, nil
}

// formatPostgresColumnDef formats a column structure into PostgreSQL DDL definition.
func formatPostgresColumnDef(col models.Column) string {
	parts := []string{"\"" + col.Name + "\""}

	// Support SERIAL / BIGSERIAL types which are syntactic sugar in PG
	if col.AutoIncrement {
		if strings.HasPrefix(strings.ToLower(col.RawType), "big") {
			parts = append(parts, "bigserial")
		} else {
			parts = append(parts, "serial")
		}
	} else {
		parts = append(parts, col.RawType)
	}

	if col.Nullable == "NO" {
		parts = append(parts, "NOT NULL")
	} else {
		parts = append(parts, "NULL")
	}

	// Default value should not be printed if column is serial (PG automatically manages serial default)
	if col.DefaultValue != nil && !col.AutoIncrement {
		parts = append(parts, "DEFAULT "+formatPostgresDefaultValue(col.RawType, *col.DefaultValue))
	}

	return strings.Join(parts, " ")
}

func formatPostgresDefaultValue(rawType, def string) string {
	defLower := strings.ToLower(def)
	// Check if default is a function/expression or a literal value
	if strings.Contains(defLower, "(") || strings.Contains(defLower, "::") {
		return def
	}
	if strings.Contains(defLower, "'") || strings.Contains(defLower, "\"") {
		return def
	}
	// Keep numeric literals unquoted, quote others
	switch strings.ToLower(strings.Split(rawType, "(")[0]) {
	case "int", "integer", "bigint", "smallint", "smallserial", "serial", "bigserial", "numeric", "decimal", "double precision", "real":
		return def
	default:
		return fmt.Sprintf("'%s'", escapeSQL(def))
	}
}

func formatPGIndexColumns(cols []string) string {
	var formatted []string
	for _, c := range cols {
		formatted = append(formatted, "\""+c+"\"")
	}
	return strings.Join(formatted, ", ")
}

func getDefStr(def *string) string {
	if def == nil {
		return "NULL"
	}
	return fmt.Sprintf("'%s'", *def)
}
